apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: was-hpa
spec:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: was